sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mzamith/docker-sandbox -f Dockerfile.dev .

script:
  - docker run -e CI=true mzamith/docker-sandbox npm run test